### ISSUE TITLE
MissingImageFileChecker fails with given paths

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#130]
in case images are referenced with given path (not only filename), checking those images fails.

**Comment by double16** [comment]
Is this saying something like:
```html
<img src="/images/bg.jpg"/>
```

Will fail if I have `$sourceDir/images/bg.jpg` ?

**Comment by gernotstarke** [comment]
currently unclear, need to check... might create some testcases or specifications... (but that might take a while, I'm currently busy with other stuff, sorry)

**Comment by double16** [comment]
Fixed
