### ISSUE TITLE
Check for missing AsciiDoc includes

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#146]
The htmlSanityCheck is great for AsciiDoc, but it does not capture one important problem: missing includes which are only output as warning while rendering the html:

> Building 33% > :asciidoctorasciidoctor: WARNING: arc42/DE/appendix-open_issues.adoc: line 15: include file not found: .../docToolchain/build/docs/openissues.adoc

a good starting point could be https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/154

(I am already experimenting with this feature for https://github.com/rdmueller/docToolchain)

**Comment by double16** [comment]
This plugin validates HTML, not AsciiDoc. Some of the examples given use AsciiDoc as the source to produce HTML, but any type of HTML generator (or even static HTML) is supported.

I think this verification belongs in the plugin that processes the AsciiDoc, such as the one you mentioned.

**Comment by rdmueller** [comment]
ok, I guess you are right. Thanx for the fast response.

I also just noticed that Asciidoc renders 

    Unresolved directive in arc42/DE/appendix-open_issues.adoc - include::../../../../build/docs/openissues.adoc[]

when an include file was not found.

So I wonder if a checker which checks for a regex would make sense as a feature?

**Comment by double16** [comment]
Seems like allowing custom rules based on regex would be a good feature.

**Comment by gernotstarke** [comment]
I propose to close this one as "wontfix" - let's keep our focus on checking html... 

@rdmueller : if you need to check AsciiDoc build, you could maybe apply a different build strategy
(e.g. break the build in case of AsciiDoc warnings)
