### ISSUE TITLE
Broken Logo in Report

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#149]
On my Win10 machine, I always get a broken logo rendered in the upper right corner of my reports.
I first thought that the logo is missing, but it is there and broken. Different tool complain differently when they are forced to open it.

The logo in the sources hier on github seems to be fine...

**Comment by rdmueller** [comment]
Just noticed that the `arrow_up` is broken in the same way.
The broken images contain (viewed with a hex editor) lots of `EF BF BD`sequences where non ascii values should be...

**Comment by gernotstarke** [comment]
can you attach a zip of such a report, pls?

**Comment by rdmueller** [comment]
great idea :-) I should have thought of it sooner...

btw: I already tried to trace back the code which copies the ressources and there is nothing suspicious in there...

[htmlchecks.zip](https://github.com/aim42/htmlSanityCheck/files/965572/htmlchecks.zip)

**Comment by rdmueller** [comment]
hm. I just searched for the plugin jar on my machine, opened it up and tried to view the images. They seem to be already broken within the plugin...
I will now try to refresh the plugin.

**Comment by rdmueller** [comment]
Still the same problem. My build fetches the plugin from

https://plugins.gradle.org/m2/gradle/plugin/org/aim42/htmlSanityCheck/0.9.6/htmlSanityCheck-0.9.6.jar

and this jar already contains the broken images...

**Comment by double16** [comment]
It's this snippet in `build.gradle`:
```groovy
processResources {
    inputs.property "version", project.version
    filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [version: project.version])
    println "after processResources, version= ${project.version}"
}
```

It's processing the images as text files. I need to skip the filter for images.

**Comment by rdmueller** [comment]
works - thanx!
