### ISSUE TITLE
localResource check if HtmlFile

### ISSUE THREAD

**Issue by soukainafir** [aim42/htmlSanityCheck#153]
The hrefs need to be valid html links and we should check the regex before processing the file. Noticed this when processing pages containing javacript scripts href=javascript:show(id) for example, this gives the following error :
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>. Cannot resolve which method to invoke for [class java.lang.String, null] due to overlapping prototypes between: [class java.lang.String, class java.lang.String] [class java.lang.String, class java.io.File]

**Comment by rdmueller** [comment]
I have the same problem with `file://`URIs...

**Comment by gernotstarke** [comment]
thx for mentioning...
Currently I cannot give an estimation for a fix-date.. but I promise to look into it :-)

**Comment by vogella** [comment]
We are also affected. cc @simonscholz.

Maybe @joschi would be able to help here again?

**Comment by ascheman** [comment]
It seems I have been running into a similar problem (at least as for the OP: a `javascript:` URL currently leads to a NPE).

**Comment by ascheman** [comment]
Hopefully resolved. Please provide more test cases when the problem persists.
