### ISSUE TITLE
add "failOnErrors" flag

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#177]

**Comment by sigdestad** [comment]
Hi.. Just tested the project, and I'm getting this error: 

`Could not set unknown property 'failOnErrors' for task ':htmlSanityCheck' of type org.aim42.htmlsanitycheck.HtmlSanityCheckTask.`

I copied the settings straight from the docs, but this does not seem to be working somehow?

**Comment by gernotstarke** [comment]
Thomas, sorry for the inconvenience. I'm currently reworking several parts of this project, but was without internet access for quite a while...

The 'failOnErrors' property has only recently been introduced, could be a version issue... 

Which version are you using?

Are you running htmlSanityChecker within a gradle build?

thanx and regards, Gernot

**Comment by sigdestad** [comment]
Hi, using the latest released version 0.9.7, building within gradle yes.

**Comment by gernotstarke** [comment]
thx. I'll try to release an updated version (containing a checker for external http/https links too!) asap (but I'm currently on holiday in remote Canada - so it may take a few days...)

In the meantime you could try to remove the "failOnError" property from your configuration.

**Comment by gernotstarke** [comment]
I just published a 1.0.0-RC-1 version to plugins.gradle.org.

You'll find a working example here: [https://github.com/aim42/htmlSanityCheckConsumer](https://github.com/aim42/htmlSanityCheckConsumer)

(it also contains a very basic version of an external http links checker)

Thanx for your interest in this plugin!

**Comment by sigdestad** [comment]
Nice, seems to be working :-)
