### ISSUE TITLE
investigate why "switch" doesn't work in BrokenHttpLinksChecker

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#180]
in method 'decideHowToTreatResponseCode' we currently use nested if-statements...

the (much clearer) version with "switch" didn't work - and I've NO idea why...

**Comment by rdmueller** [comment]
can you show me the code? I would love to debug this switch statement...

**Comment by gernotstarke** [comment]
Already done...

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.
