### ISSUE TITLE
add spellChecker

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#183]
finding candidates for misspelled words

**Comment by rdmueller** [comment]
what will you do with false positives?

I t think this is a great feature,. but for another tool/checker...

**Comment by rdmueller** [comment]
this would be a nice feature for a sonarqube plugin...

btw: this is already on my docToolchain feature list among with features like a readability and sentence complexity score...

**Comment by gernotstarke** [comment]
in my opinion "sanity" includes various aspects, and "spelling" or other linguistic stuff can be seen among those.

You're perfectly right - it's gonna be really difficult, and imho will require enhancing the possible checking results (as spellchecks produce more suggestions or hints than errors...)

**Comment by rdmueller** [comment]
absolutly, sanity is also spellcheck. my comment was more about the type of check we currently have - which is basically unit testing.

maybe the spellcheck could be a sonarqube plugin hosted under the htmlsanitychecker umbrella?

**Comment by gernotstarke** [comment]
one idea could be to provide a separate repo/project for the SonarQube plugin, which utilizes the HtmlSanityChecker "business logic"...
