### ISSUE TITLE
make hsc maven plugin

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#196]
for example similar to:

https://dzone.com/articles/a-simple-maven-3-
plugin

[] create "glue code"
[] create sample maven pom in htmlSanityCheck-Consumer repository

**Comment by uniqueck** [comment]
Hi Gernot,

why is it not possible to create an instance of Configuration class (only one private constructor)? I would like to start implement an maven plugin, but I would like to implement it in an separate repository. So i would like to use htmlsanitycheck as a dependency and wrapped it with a maven plugin.

**Comment by gernotstarke** [comment]
Constantin,
I don't really care where you implement the maven stuff - but it's likely people expect it in the original repo... In case it's easier for you, I could give you commit/push rights in the repo (as I currently don't have the time to check/verify PRs)

**Comment by ascheman** [comment]
Did you proceed on this idea, @uniqueck?
Meanwhile we have modularized HSC (cf. #309), which is still work-in-progress and are aiming at adding a Maven plugin (cf. #314). 

I will close this issue. If there are any outstanding contributions, please try to refer to #314 instead.
