### ISSUE TITLE
External Links Checker Problem

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#218]
When I take a look at this report: https://docs-as-co.de/report/htmlchecks/index.html
I get the feeling that sometimes a head-request is not enough.

For instance, the checks for those two URLs fails, but both URLs seem to be availalbe...

Error: https://idratherbewriting.com/ returned statuscode 403.
Error: https://justwriteclick.com/ returned statuscode 503.

**Comment by gernotstarke** [comment]
same as #219 - sorry for the duplication.

**Comment by gernotstarke** [comment]
should be fixed in 1.0.0-RC-2
