### ISSUE TITLE
update readme for new config options

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#225]
especially the timeout and http status code options should be clarified!

**Comment by ascheman** [comment]
Cf. 
- [Timeout](https://github.com/aim42/htmlSanityCheck/blob/695c7f2ce735884b340fba1e5968e909f3329127/htmlSanityCheck-gradle-plugin/README.adoc?plain=1#L107)
- [Status Code Options](https://github.com/aim42/htmlSanityCheck/blob/695c7f2ce735884b340fba1e5968e909f3329127/htmlSanityCheck-gradle-plugin/README.adoc?plain=1#L137) (ff.)
