### ISSUE TITLE
problem with generatePDF

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#226]
the asciidoc source currently pose a problem on generatePDF.

Because of the line

    image:http://badge.waffle.io/aim42/{project}.png?label=bug&title=bugs[link="{project-bugs}"]

`gradlew generatePDF` produces the following error message on a windows system:

    (IOError) Die Syntax fⁿr den Dateinamen, Verzeichnisnamen oder die DatentrΣgerbezeichnung ist falsch

Solution could be to conditional skip this badge for PDFs

**Comment by rdmueller** [comment]
Just checked it with bash on ubuntu: here I get a different warning:

    asciidoctor: WARNING: image to embed not found or not readable: http://badge.waffle.io/aim42/htmlSanityCheck.png?label=bug&amp;title=bugs

So, it seems to be mainly a problem with some file name in a windows file system. But even when run on linux, it can't fetch and render the image.

**Comment by rdmueller** [comment]
Workaround:
deaktivate identified lines when rendering as PDF by encapsulating them with

    ifndef::backend-pdf[]
        ...
    endif::[]

**Comment by gernotstarke** [comment]
I suggest to remove this damned badge, if it creates that many problems...

**Comment by gernotstarke** [comment]
done, removed line
