### ISSUE TITLE
add contributor avatars to each section

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#250]
see

![image](https://user-images.githubusercontent.com/1856308/47785377-d5b9ca80-dd08-11e8-86be-57868b55952d.png)

as example

**Comment by gernotstarke** [comment]
I oppose - it does not value, does it?

It's nice for WJAX, but I'll remove it afterwards...

let's concentrate on stuff that's adding value for stakeholders :-)

**Comment by rdmueller** [comment]
ok - we have a docToolchain demo for the JAX - this should then be enough.

Regarding the value - there is not much value for the reader but I guess there is some value for the contributors...
