### ISSUE TITLE
create website with all documentation

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#258]
create a "full-scale" site that contains all parts of the hsc documentation:

[ ] user-doc
[x] developer-doc
[x] architecture-doc
[x| meta (docs about the docs)
[x] Host that site on hsc.aim42.org

**Comment by gernotstarke** [comment]
[ ] add favicon :-)

**Comment by gernotstarke** [comment]
Netlify to the rescue -

**Comment by ascheman** [comment]
Does it make sense to replace the contents of hsc.aim42.org with the [generated GH pages](https://aim42.github.io/htmlSanityCheck/) from this build?

**Comment by gernotstarke** [comment]
yes, absolutely...

in some distant future I would re-design the index-page... but that's nitpicking...

thanx

**Comment by ascheman** [comment]
> 


> yes, absolutely...

Great, this must be mostly performed on your side, thanks!
But I am happy to help with more PRs regarding contents and clean up of old fragments wrt. site publication on Netlify.

**Comment by gernotstarke** [comment]
I need to change the dns settings for the subdomain, if I remember correctly.

Otherwise, we imho need an CNAME, don't we?

**Comment by ascheman** [comment]
Yes, per my understanding a CNAME entry should do. 
Then the DNS name needs to be configured in Settings->Pages of the GH project.

**Comment by gernotstarke** [comment]
just created the CNAME record...

**Comment by ascheman** [comment]
Thanks for your support @gernotstarke, HSC documentation is now available with recent updates on https://hsc.aim42.org.
