### ISSUE TITLE
compileTestGroovy target fails

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#262]
just a reminder:

* tested build with gradle v5.0
* message was:

    Configure project :
    This version of Gradle requires version 2.0.2 of 
    the build scan plugin or later. 
    Please see https://gradle.com/scans/help/gradle-incompatible-plugin-version for more information.
after processResources config, version= 1.0.0-RC-3

**Comment by gernotstarke** [comment]
update: even with gradle build-scan plugin version set to 2.0.2, build still fails.

**Comment by rdmueller** [comment]
It seems that the version 2.4 of groovy in the classpath cause some problems. 
This is a dependency of Spock.
I currently try to upgrade Spock - first results look good.

**Comment by gernotstarke** [comment]
went for the second option.
