### ISSUE TITLE
allow the list of checks to be configurable

### ISSUE THREAD

**Issue by jechlin** [aim42/htmlSanityCheck#265]
Some of the checks take a long... when starting with this we initially only want a couple of the fast-running checks.

NB - we can contribute a PR for this and my other request if you are amenable.

**Comment by gernotstarke** [comment]
Thx for your comments, we'd love PRs....

Thx,Gernot 

Dr. Gernot Starke
+49-177-7282570
gs@gernotstarke.de
www.gernotstarke.de

Von einem mobilen Geraet gesendet - bitte verzeihen Sie eventuelle Tippfehler.

**Comment by gernotstarke** [comment]
afaik the "external links checker" is currently configured.

Please note also #185 (checkers to be detected automatically) - the two might be somewhat related.
