### ISSUE TITLE
valid URL yields "unknown host with href" message

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#272]
as pointed out by @mernst the URL "https://douglascayers.com/2015/05/30/how-to-set-custom-java-path-after-installing-jdk-8/" leads to a "unknown host with href" error, although its syntactically valid AND functioning (http response code 200).

Created a regression test in `BrokenHttpLinksCheckerSpec.groovy`.

**Comment by gernotstarke** [comment]
Java wraps an "sun.security.Validator.ValidatorException" in the overly general "UnknownHost" exception.

Seems to be rooted in certain (often self-signed) certificates on the webserver. Browsers and other clients can cope with that, but java complains. 

In this specific case the cert has been issued by LetsEncrypt.

I see two possible solutions:

1. introduce a configurable "whitelist" of URL's that will be excluded from htmlSanityChecks
2. deep-dive into java https protocol handshaking and come up with a general solution.

Considering my current situation, I'll at most go for nr 1 - any help appreciated.

**Comment by double16** [comment]
You could configure Java to not validate SSL certs. It's about 2-3 lines of code. I did it some years back, a Google search would probably yield results.

**Comment by mernst** [comment]
Either solution would be fine with me.

**Comment by gernotstarke** [comment]
thanx to suggestion by @double16 I'll try to implement an "UnsafeHttpConnection", which ignores the certificates...

My experiments showed that this problem does NOT exist in Java 11 and Java 12... at least for several tests I got a 200 instead of the nasty exception.

**Comment by gernotstarke** [comment]
(hopefully) fixed by adding an insecure always-trusting TrustManager class... that ignores the ssl certificates.

In my tests on the Randoop fork all external links are now tested ok (@mernst - please verify)

**Comment by mernst** [comment]
This works!  Thank you.
