### ISSUE TITLE
broken link to arc docs

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#275]
is: (404)
https://rawgit.com/aim42/htmlSanityCheck/gh-pages/hsc_arc42.html

should be: 
https://hsc.aim42.org/documentation/hsc_arc42.html

PR is coming in a moment

**Comment by gernotstarke** [comment]
this is a very old part of the documentation... thx for spotting.

**Comment by ascheman** [comment]
Is this still an issue, @rdmueller? 
In which (generated) document do you see the broken links?

**Comment by ascheman** [comment]
Should be resolved by #332
