### ISSUE TITLE
upgrade jsoup to 1.13

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#287]
https://jsoup.org/news/release-1.13.1

should be significantly faster now...

**Comment by oliva123456** [comment]
sorry for mixing up merge-requests for this issue and issue 307 within the pull-request (last github activities have been a while ago): https://github.com/aim42/htmlSanityCheck/pull/307

**Comment by ascheman** [comment]
Fixed by #307
