### ISSUE TITLE
Links which ends with ) doesn't work

### ISSUE THREAD

**Issue by FelixGeisler** [aim42/htmlSanityCheck#298]
Links which ends with closing round brackets will lead to an error.

e.g.: 
https://en.wikipedia.org/wiki/Qt_(software) 
will lead to:
Error: https://en.wikipedia.org/wiki/Qt_(software returned statuscode 404.

**Comment by gernotstarke** [comment]
Felix, due to personal and professional circumstances I cannot deal with this problem in the forseable future, sorry.
You like to submit a PR for it?

**Comment by FelixGeisler** [comment]
Hey Gernot,

unfortunately, I don't have time for that at the moment either. But hopefully in a few days.

**Comment by ascheman** [comment]
To me it looks like the problem has vanished. Could you please try to reproduce and give a little more context (which version of HSC) and perhaps even a test case, @FelixGeisler?
