### ISSUE TITLE
GFileUtils will be removed in Gradle 9

### ISSUE THREAD

**Issue by sciencewhiz** [aim42/htmlSanityCheck#305]
GFileUtils is used at https://github.com/aim42/htmlSanityCheck/blob/main/src/main/groovy/org/aim42/htmlsanitycheck/report/HtmlReporter.groovy#L68

In gradle 8, it's deprecated and will be removed in Gradle 9. https://docs.gradle.org/8.1/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations

One alternative is Apache Commons FileUtils, which GFileUtils is a wrapper of.

**Comment by gernotstarke** [comment]
thanx for letting us know.

I'm currently not able to update the htmlSanityCheck myself - help would be appreciated!

**Comment by oliva123456** [comment]
created pull request https://github.com/aim42/htmlSanityCheck/pull/308

**Comment by ascheman** [comment]
Resolved by #308
