### ISSUE TITLE
Port of HtmlSanityChecker from Groovy to Java

### ISSUE THREAD

**Issue by truhroth** [aim42/htmlSanityCheck#312]
The core module is currently written mostly using groovy. This leads to a dependency to groovy even if you do not use grade, which brings groovy itself.

The goal of this ticket, is to port the core code to pure java and reduce the runtime depe3ndencys. The aim is to only have a runtime dependency to the html parser.

The text code is also written in groovy. Since it does not forces a runtime dependency to groovy, this code is not refactored in this ticket.

**Comment by ascheman** [comment]
Merged all changes to develop
