### ISSUE TITLE
Replace incorporated net.ricecode components

### ISSUE THREAD

**Issue by ascheman** [aim42/htmlSanityCheck#330]
As a developer of HSC I would like to get use the [Java String Similarity](https://github.com/rrice/java-string-similarity) library and drop the incorporated version of it from my source (as it meanwhile became publicly available on [Maven Central](https://central.sonatype.com/artifact/net.ricecode/string-similarity)).

**Comment by Prankurtiwari** [comment]
Hi @ascheman, I would like to discuss and work on this enhancement. Let me know

**Comment by ascheman** [comment]
Thanks a lot, @Prankurtiwari, please add the library as new dependency and drop the overtaken classes. I hope it is not much more than this?

Are you on (the Hacktoberfest) [Discord](https://discord.gg/hacktoberfest)? You can reach out to me ([gerdaschemann](https://discord.com/users/904280116216098846)) so we could have a chat if you run into problems (or if you need any other support).

**Comment by Prankurtiwari** [comment]
Thanks for quick response @aschema. I will look into the project a

> Thanks a lot, @Prankurtiwari, please add the library as new dependency and drop the overtaken classes. I hope it is not much more than this?
> > Are you on (the Hacktoberfest) [Discord](https://discord.gg/hacktoberfest)? You can reach out to me ([gerdaschemann](https://discord.com/users/904280116216098846)) so we could have a chat if you run into problems (or if you need any other support).



> Thanks a lot, @Prankurtiwari, please add the library as new dependency and drop the overtaken classes. I hope it is not much more than this?
> 
> Are you on (the Hacktoberfest) [Discord](https://discord.gg/hacktoberfest)? You can reach out to me ([gerdaschemann](https://discord.com/users/904280116216098846)) so we could have a chat if you run into problems (or if you need any other support).

Thanks @ascheman for the quick response. I will try to resolve this issue and raise the PR.

Yes i am on the discord Hacktoberfest server. I have sent you the request and pinged you on discord. I will let you know if I need any assistance. Thanks :)

**Comment by Prankurtiwari** [comment]
Change PR : https://github.com/aim42/htmlSanityCheck/pull/351/files
Please review
