### ISSUE TITLE
Use mocks for remote/integration testing

### ISSUE THREAD

**Issue by ascheman** [aim42/htmlSanityCheck#331]
As developer of HSC I would like to use a mock service to test for misc. external resources as the *real resources* are sometimes not stable which leads to frequent flaky errors and unstable builds.

**Comment by RehanChalana** [comment]
Hey @ascheman 

I have some experience with testing. I would love to contribute!

Can you help me on where to start from

**Comment by ascheman** [comment]
Hi @RehanChalana,

thanks a lot, I appreciate your offer.

My idea would be to mock away external services which are used for testing (and are somewhat unstable in their availability).
If you take [htmlSanityCheck-core/src/test/groovy/org/aim42/htmlsanitycheck/check/BrokenHttpLinksCheckerSpec.groovy](https://github.com/aim42/htmlSanityCheck/blob/0e8c1b7d6d509bfe140de84f205bd87ad2538037/htmlSanityCheck-core/src/test/groovy/org/aim42/htmlsanitycheck/check/BrokenHttpLinksCheckerSpec.groovy) as a starting point, you will find several good and bad URLs referring to external sites. If you run the test case while not connected to the Internet, it will run into (false) errors. 

Hence, I would like to start a (local) mock service and run the tests against the mocked endpoints. Suitable technologies could be Wiremock, and perhaps Testcontainers? But I am happy if you see another approach.

**Comment by RehanChalana** [comment]
Thank you so much for the detailed response!

To start, I am working on [htmlSanityCheckcore/src/test/groovy/org/aim42/htmlsanitycheck/check/BrokenHttpLinksCheckerSpec.groovy](https://github.com/aim42/htmlSanityCheck/blob/0e8c1b7d6d509bfe140de84f205bd87ad2538037/htmlSanityCheck-core/src/test/groovy/org/aim42/htmlsanitycheck/check/BrokenHttpLinksCheckerSpec.groovy) I’m trying to use WireMock as you mentioned, but I’ve encountered an issue since its latest version requires Java 11 or higher. I’m still figuring it out but its fun!

**Comment by ascheman** [comment]
Are you on (the Hacktoberfest) [Discord](https://discord.gg/hacktoberfest)? You can reach out to me ([gerdaschemann](https://discord.com/users/904280116216098846)) so we could have a chat about the problems you encounter (or if you need any other support).

I am also happy if you will contribute to the [development documentation](https://hsc.aim42.org/development/development-intro.html) of the project if you manage to solve your issues. A second PR wrt. to docs could increase your Hacktoberfest score.

**Comment by RehanChalana** [comment]
Yes i am on discord! as well as participating in hacktoberfest!

I sent you a friend request on discord as well. my username is rc__22.

Thanks !
