### ISSUE TITLE
Add BrokenHttpLinksChecker

### ISSUE THREAD

**Issue by gernotstarke** [aim42/htmlSanityCheck#34]
child of #171

**Comment by gernotstarke** [comment]
use GPARS for parallel execution of checks...

http://gpars.codehaus.org/

**Comment by marcphilipp** [comment]
I would be very interested in this feature! We have a [user guide](http://junit.org/junit5/docs/snapshot/user-guide/) that includes quite a few external references, e.g. to code in a GitHub repo. Whenever someone renames a referenced class the link breaks. Is there a chance this feature will get added in the near future? Would a contribution be accepted? Unfortunately, my Groovy skills are very limited…

**Comment by gernotstarke** [comment]
Marc, thanx for your interest.
Contributions are **really** welcome. I'll give this a higher prio - and see what I can do...

**Comment by gernotstarke** [comment]
https://github.com/rackerlabs/gradle-linkchecker-plugin implements several checks for external links - maybe we could re-use or reference that...

**Comment by gernotstarke** [comment]
further info: http://www.oracle.com/webfolder/technetwork/tutorials/obe/java/httpThreadLink/HttpClient.html

**Comment by gernotstarke** [comment]
done, will be live with Version 1.0.0-RC-2 (RC-1 was highly incomplete)
